### ISSUE TITLE
[Suggestion/Request] Full Pattern Encoding functionality with EMI?

### ISSUE THREAD

**Issue by MechanosG** [blocovermelho/ae2-emi-crafting#7]
Hello.  Here's my situation.  The last few versions of the Prominence II RPG modpack switched from REI to EMI, and the last version (2.7.6) added AE2 EMI Crafting Integration 1.0.1.

Normally using REI (and presumably JEI), I can add new recipes to the pattern encoding terminal by just looking up that recipe and clicking the add button.  It doesn't matter if I have the items available or not - it just lets me make the pattern.

But it seems currently with EMI and EMI Crafting Integration, if you use the pattern encoding terminal (on a multiplayer server if that makes any difference), look up a recipe in EMI with AE2 EMI Crafting Integration active, then try to import it over to the pattern encoding terminal like you would in REI, EMI doesn't seem to see the pattern encoding terminal as something it can send the recipe to, so no usable button is displayed, whether you have the items or not.

Without JEI, it looks like this. (I have 40 birch planks in storage, yet they show up red as well)
![Screenshot_20240228_211750](https://github.com/blocovermelho/ae2-emi-crafting/assets/4360512/16f123be-d9bf-4385-a2d4-a59dda881ac6)

I also tried adding JEI client side, to see if that would make a difference.  That seemed to help with blue highlighting and usage of existing craftable patterns, but didn't help with the pattern encoding terminal.  The bottom button to add the recipe just disappears completely, and I am still forced to manually add items to the crafting grid in the pattern coding terminal, if I want to make a new pattern.

Help greatly appreciated lol.  Unless I'm missing something, is this with-in the scope of this mod to suggest/request?

**Comment by roridev** [comment]
This is technically am extension of a feature request (#2) I've filled a **while** back, it *is* on the scope of the mod. I Just hadn't had time to add that feature since I lacked knowledge of EMI's APIs to do so.

Since this is *way* more detailed then what I had documented before I'll leave this here.
It should be possible to do this, but I don't have an ETA. Afaik I don't have anything else thats higher priority then this so I should get to doing this sooner rather then later.

**Comment by MechanosG** [comment]
I _almost_ posted this there first.  But then I kept re-reading the part about EMI not seeing the ME system, and wasn't 100% certain it was the same thing (and didn't wanna risk annoying anyone), so decided to create a new issue.  Sorry lol.  Thanks for the fast response though.  I've visited the Discord of the mentioned modpack, and there are a lot of AE2 fans currently unsure what to do currently, so I'm happy to get a response.  Best of luck.  :)

**Comment by roridev** [comment]
So... yeah, I got drag and drop support working (since that is like a breaking thing for making processing patterns manually) 
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/12b8bccb-cfc5-431b-9563-2ddd56836ff0)

And the "Fill recipe" button now works on the Pattern Crafting terminal.
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/d5c44b40-f068-4168-a482-dbbb5acc1cbb)

I'm just doing some final testing to see if things work as intended.
So far what is broken is that processing patterns are treated as crafting patterns, which can be annoying and dragging fluids still doesn't work so fluid crafting is broken.

**Comment by roridev** [comment]
Fixed
--- 
Dev : 9575acd4ebaa5e3a006ca45ac87ab616e2413775
Modrinth : [1.2.0](https://modrinth.com/mod/ae2-emi-crafting/version/1.2.0)
CurseForge: Blocked

**Comment by MechanosG** [comment]
I'm a little slow responding, but..  thank you very much for this update, and all of the other updates you've made recently.  Being able to use AE2 properly with EMI has been great.  Much appreciated.
